server:
  port: 8765
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
#      routes:
#        - id: account_route
#          uri: lb://account
#          predicates:
#            - Path=/account/**
#          filters:
#            - RewritePath=/account/(?<path>.*), /$\{path}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka